package challenge.exception;

public class CSVParseException extends Exception {
    public CSVParseException(String message) {
        super(message);
    }

    public CSVParseException(String message, Throwable cause) {
        super(message, cause);
    }
}
